### ISSUE TITLE
Уменьшить связанность классов

### ISSUE THREAD

**Issue by ravilASH** [cargovova/Battleship#1]
Изменить связи .
Контроллер знает только про игру, игра знает про поле и только поле знает про ячейки и возможные их значения. Управляющие сигналы идут той же дорогой. Контроллер говорит игре что в нее сделан ход, она просит у поля значение ячейки, сама решает на что ее поменять, после чего она просит поле изменить значение ячейки на новое.

Conroller - Game -Field-Sell . 

Знание котроллера что поле устроено каким-то особым образом недопустимо, равно как и знание игры об этом, в то же время поле не знает что делать с конкретным значением ячейки при попадании, это знает только игра

https://github.com/cargovova/Battleship/blob/a9aa5aa7d87d1a6d3e6207a38fa9de09605713cb/src/controller/Controller.php#L30

**Comment by cargovova** [comment]
10 | 3.12.18

**Comment by cargovova** [comment]
100 %

**Comment by ravilASH** [comment]
Зачем в этой функции setShipsState переменная $state там можно проставить какой-то другой статус? Это пример той самой связи, которую я просил убрать, почему не ячейка решает какой статус будет у нее инициирующим а фронт? тем более без каких либо проверок
