### ISSUE TITLE
Во всем коде убрать волшебные строки и числа, уйти к константам

### ISSUE THREAD

**Issue by ravilASH** [cargovova/Battleship#2]
Не использовать никаких строк и цифр, только константы
Антипаттерн волшебные цифры https://refactoring.guru/ru/replace-magic-number-with-symbolic-constant

https://github.com/cargovova/Battleship/blob/a9aa5aa7d87d1a6d3e6207a38fa9de09605713cb/src/controller/Controller.php#L30

**Comment by ravilASH** [comment]
Здесь тоже, каждую константу сделать отдельной, можно сделать метод getAllStates() если нужно

**Comment by cargovova** [comment]
1 | 3.12.18

**Comment by cargovova** [comment]
200%
Нет комита к этому issues, так как он был выполнен в рамках #1

**Comment by ravilASH** [comment]
Эта строка содержит волшебное слово hit

https://github.com/cargovova/Battleship/blob/f23a2b07d8af3089d8d4fe701ff90957edbb5e1d/src/model/Game.php#L63

result => self::RESULT_ACTION['hit']
